// <auto-generated />
using System;
using Fundo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundo.Infrastructure.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20260702225759_AddAdditionalLoanSeeds")]
    partial class AddAdditionalLoanSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fundo.Domain.Loans.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9d11d7c-96c0-4028-a695-5b97a1236101"),
                            AnnualInterestRate = 8.5m,
                            ApplicantEmail = "john.doe@example.com",
                            ApplicantName = "John Doe",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 25000m,
                            PrincipalAmount = 25000m,
                            Status = "Active",
                            TermMonths = 60
                        },
                        new
                        {
                            Id = new Guid("b7809481-ac07-472b-84d9-71726ab24470"),
                            AnnualInterestRate = 6.75m,
                            ApplicantEmail = "jane.smith@example.com",
                            ApplicantName = "Jane Smith",
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 15000m,
                            PrincipalAmount = 15000m,
                            Status = "Active",
                            TermMonths = 36
                        },
                        new
                        {
                            Id = new Guid("9a8cd754-c81a-4bb9-98d9-b4a4e86155ef"),
                            AnnualInterestRate = 10.25m,
                            ApplicantEmail = "robert.johnson@example.com",
                            ApplicantName = "Robert Johnson",
                            CreatedAtUtc = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 50000m,
                            PrincipalAmount = 50000m,
                            Status = "Active",
                            TermMonths = 84
                        },
                        new
                        {
                            Id = new Guid("e3631e12-8a99-4741-988b-80d8548b85d6"),
                            AnnualInterestRate = 7.2m,
                            ApplicantEmail = "alicia.martinez@example.com",
                            ApplicantName = "Alicia Martinez",
                            CreatedAtUtc = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 18000m,
                            PrincipalAmount = 18000m,
                            Status = "Active",
                            TermMonths = 48
                        },
                        new
                        {
                            Id = new Guid("9edbaab6-a4dd-4640-bb74-9979b6ff0d8a"),
                            AnnualInterestRate = 9.1m,
                            ApplicantEmail = "michael.chen@example.com",
                            ApplicantName = "Michael Chen",
                            CreatedAtUtc = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 32000m,
                            PrincipalAmount = 32000m,
                            Status = "Active",
                            TermMonths = 72
                        },
                        new
                        {
                            Id = new Guid("1df28770-bef2-473b-bcb2-dc1de930f3c2"),
                            AnnualInterestRate = 5.95m,
                            ApplicantEmail = "priya.patel@example.com",
                            ApplicantName = "Priya Patel",
                            CreatedAtUtc = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 12000m,
                            PrincipalAmount = 12000m,
                            Status = "Active",
                            TermMonths = 24
                        },
                        new
                        {
                            Id = new Guid("f897e9d6-c0b6-4667-bc04-359d506805da"),
                            AnnualInterestRate = 8.95m,
                            ApplicantEmail = "elena.garcia@example.com",
                            ApplicantName = "Elena Garcia",
                            CreatedAtUtc = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 27500m,
                            PrincipalAmount = 27500m,
                            Status = "Active",
                            TermMonths = 60
                        },
                        new
                        {
                            Id = new Guid("f7c15d77-10ce-40b6-bd97-66c0a1025f3c"),
                            AnnualInterestRate = 11.5m,
                            ApplicantEmail = "daniel.kim@example.com",
                            ApplicantName = "Daniel Kim",
                            CreatedAtUtc = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 41000m,
                            PrincipalAmount = 41000m,
                            Status = "Active",
                            TermMonths = 84
                        },
                        new
                        {
                            Id = new Guid("5ee054d0-8216-4fa8-8d65-f4418cf49c8e"),
                            AnnualInterestRate = 4.8m,
                            ApplicantEmail = "sofia.rivera@example.com",
                            ApplicantName = "Sofia Rivera",
                            CreatedAtUtc = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 9500m,
                            PrincipalAmount = 9500m,
                            Status = "Active",
                            TermMonths = 18
                        },
                        new
                        {
                            Id = new Guid("4d5c57eb-f233-4fa3-8ab9-e57a7631dc99"),
                            AnnualInterestRate = 7.75m,
                            ApplicantEmail = "marcus.brown@example.com",
                            ApplicantName = "Marcus Brown",
                            CreatedAtUtc = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 22000m,
                            PrincipalAmount = 22000m,
                            Status = "Active",
                            TermMonths = 48
                        },
                        new
                        {
                            Id = new Guid("a0034e8a-58c9-4431-a53b-2a1f05be9a19"),
                            AnnualInterestRate = 9.85m,
                            ApplicantEmail = "hannah.lee@example.com",
                            ApplicantName = "Hannah Lee",
                            CreatedAtUtc = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 36000m,
                            PrincipalAmount = 36000m,
                            Status = "Active",
                            TermMonths = 72
                        },
                        new
                        {
                            Id = new Guid("b834149b-e9be-4c74-a7b0-82e066db3618"),
                            AnnualInterestRate = 6.35m,
                            ApplicantEmail = "omar.hassan@example.com",
                            ApplicantName = "Omar Hassan",
                            CreatedAtUtc = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 14500m,
                            PrincipalAmount = 14500m,
                            Status = "Active",
                            TermMonths = 36
                        },
                        new
                        {
                            Id = new Guid("5d5998e9-1e22-4b7d-858b-3cbf9dc7da9d"),
                            AnnualInterestRate = 8.15m,
                            ApplicantEmail = "grace.wilson@example.com",
                            ApplicantName = "Grace Wilson",
                            CreatedAtUtc = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 28500m,
                            PrincipalAmount = 28500m,
                            Status = "Active",
                            TermMonths = 60
                        },
                        new
                        {
                            Id = new Guid("63992150-4aa2-4eeb-a3d1-778ebb0150c3"),
                            AnnualInterestRate = 7.05m,
                            ApplicantEmail = "ethan.brooks@example.com",
                            ApplicantName = "Ethan Brooks",
                            CreatedAtUtc = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 19500m,
                            PrincipalAmount = 19500m,
                            Status = "Active",
                            TermMonths = 48
                        },
                        new
                        {
                            Id = new Guid("43e372c8-1339-420d-9a50-a2d08bec7d99"),
                            AnnualInterestRate = 10.75m,
                            ApplicantEmail = "nadia.flores@example.com",
                            ApplicantName = "Nadia Flores",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 47000m,
                            PrincipalAmount = 47000m,
                            Status = "Active",
                            TermMonths = 84
                        });
                });

            modelBuilder.Entity("Fundo.Domain.Loans.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDateUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Fundo.Domain.Loans.Payment", b =>
                {
                    b.HasOne("Fundo.Domain.Loans.Loan", null)
                        .WithMany("Payments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fundo.Domain.Loans.Loan", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
