// <auto-generated />
using System;
using Fundo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundo.Infrastructure.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    partial class LoanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fundo.Domain.Loans.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9d11d7c-96c0-4028-a695-5b97a1236101"),
                            AnnualInterestRate = 8.5m,
                            ApplicantEmail = "john.doe@example.com",
                            ApplicantName = "John Doe",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 25000m,
                            PrincipalAmount = 25000m,
                            Status = "Active",
                            TermMonths = 60
                        },
                        new
                        {
                            Id = new Guid("b7809481-ac07-472b-84d9-71726ab24470"),
                            AnnualInterestRate = 6.75m,
                            ApplicantEmail = "jane.smith@example.com",
                            ApplicantName = "Jane Smith",
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 15000m,
                            PrincipalAmount = 15000m,
                            Status = "Active",
                            TermMonths = 36
                        },
                        new
                        {
                            Id = new Guid("9a8cd754-c81a-4bb9-98d9-b4a4e86155ef"),
                            AnnualInterestRate = 10.25m,
                            ApplicantEmail = "robert.johnson@example.com",
                            ApplicantName = "Robert Johnson",
                            CreatedAtUtc = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBalance = 50000m,
                            PrincipalAmount = 50000m,
                            Status = "Active",
                            TermMonths = 84
                        });
                });

            modelBuilder.Entity("Fundo.Domain.Loans.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDateUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Fundo.Domain.Loans.Payment", b =>
                {
                    b.HasOne("Fundo.Domain.Loans.Loan", null)
                        .WithMany("Payments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fundo.Domain.Loans.Loan", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
